import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Biometric Data Policy - SMB Chat',
  description: 'Biometric Data Policy for SMB Chat, an AI chatbot platform by Start My Business Inc.',
}

export default function BiometricPage() {
  return (
    <article className="prose prose-gray max-w-none prose-headings:scroll-mt-24">
      <div className="mb-10">
        <h1 className="text-3xl sm:text-4xl font-bold text-gray-900 mb-3">Biometric Data Policy</h1>
        <p className="text-sm text-gray-500">
          Effective Date: April 5, 2026 | Last Updated: April 5, 2026
        </p>
      </div>

      <p>
        This Biometric Data Policy explains how Start My Business Inc. ("Company," "we," "us," or "our") handles
        biometric data in connection with the SMB Chat Service ("Service"). This policy applies to account holders
        who enable voice chat features and to end users who interact with voice-enabled chatbots.
      </p>

      <div className="rounded-xl border border-amber-200 bg-amber-50 p-5 my-8 not-prose">
        <p className="text-sm font-semibold text-amber-800 mb-1">Important</p>
        <p className="text-sm text-amber-700">
          Biometric data processing occurs only when the voice chat feature is enabled by the account holder.
          Text-only chatbots do not collect or process biometric data.
        </p>
      </div>

      {/* 1. What We Collect */}
      <section id="bio-what-we-collect">
        <h2 className="text-xl font-bold text-gray-900 mt-10 mb-4">1. What Biometric Data We Collect</h2>

        <h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">1.1 Voice Data</h3>
        <p>
          When the voice chat feature is enabled and an end user initiates a voice conversation, the Service
          processes the following:
        </p>
        <ul>
          <li><strong>Audio recordings:</strong> Voice input from the end user, captured through the browser's microphone API</li>
          <li><strong>Voice characteristics:</strong> Acoustic features extracted during speech-to-text processing, including pitch, cadence, and vocal patterns</li>
          <li><strong>Transcriptions:</strong> Text transcriptions of voice input generated by our speech-to-text service</li>
        </ul>

        <h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">1.2 What We Do NOT Collect</h3>
        <ul>
          <li>We do not create voiceprints or voice templates for identification purposes</li>
          <li>We do not use voice data for speaker recognition, verification, or authentication</li>
          <li>We do not collect facial geometry, fingerprints, retinal scans, or other biometric identifiers</li>
          <li>We do not use biometric data for surveillance or tracking purposes</li>
        </ul>
      </section>

      {/* 2. Purpose of Collection */}
      <section id="bio-purpose">
        <h2 className="text-xl font-bold text-gray-900 mt-10 mb-4">2. Purpose of Collection</h2>
        <p>We process voice data solely for the following purposes:</p>
        <ul>
          <li><strong>Speech-to-text conversion:</strong> Converting the end user's spoken words into text so the chatbot can process and respond to the query</li>
          <li><strong>Text-to-speech response:</strong> Generating spoken responses from the chatbot using synthesized speech (this does not involve the end user's biometric data)</li>
          <li><strong>Conversation logging:</strong> Storing text transcriptions of voice conversations for the account holder's analytics and quality review (if enabled)</li>
        </ul>
        <p>
          We do not use voice data to build biometric profiles, sell to third parties, or use for any purpose
          beyond providing the voice chat functionality described above.
        </p>
      </section>

      {/* 3. Storage & Retention */}
      <section id="bio-storage">
        <h2 className="text-xl font-bold text-gray-900 mt-10 mb-4">3. Storage & Retention</h2>

        <h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">3.1 Audio Recordings</h3>
        <p>
          Raw audio recordings are processed in real-time for speech-to-text conversion and are <strong>not
          permanently stored</strong>. Audio data is held in temporary memory only for the duration of the
          processing request (typically under 30 seconds) and then automatically deleted.
        </p>

        <h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">3.2 Transcriptions</h3>
        <p>
          Text transcriptions of voice conversations are stored as part of the conversation log for the duration
          specified in the account holder's data retention settings (default: 90 days). Transcriptions are stored
          encrypted at rest using AES-256 encryption.
        </p>

        <h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">3.3 Voice Characteristics</h3>
        <p>
          Acoustic features extracted during processing are transient and not stored after the speech-to-text
          conversion is complete. They exist only in memory during the active processing window.
        </p>

        <h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">3.4 Storage Location</h3>
        <p>
          All data processing occurs on servers located in the United States. Audio data is transmitted to our
          speech-to-text provider using encrypted connections (TLS 1.2+).
        </p>
      </section>

      {/* 4. Consent Mechanisms */}
      <section id="bio-consent">
        <h2 className="text-xl font-bold text-gray-900 mt-10 mb-4">4. Consent Mechanisms</h2>

        <h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">4.1 End User Consent</h3>
        <p>
          Before any voice data is captured, the end user must take the following affirmative steps:
        </p>
        <ul>
          <li>Click or tap the microphone button in the chat widget to initiate voice mode</li>
          <li>Grant browser-level microphone permission when prompted by the browser</li>
          <li>Acknowledge the voice data notice displayed in the chat widget before the first voice interaction</li>
        </ul>
        <p>
          Voice capture does not begin until the end user has completed all three steps. The end user can revoke
          microphone access at any time through their browser settings, which immediately stops all voice data
          collection.
        </p>

        <h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">4.2 Account Holder Responsibility</h3>
        <p>
          Account holders who enable the voice chat feature are responsible for:
        </p>
        <ul>
          <li>Ensuring their privacy policy discloses the collection and processing of voice data</li>
          <li>Obtaining any additional consent required by laws applicable to their end users</li>
          <li>Complying with biometric data laws in jurisdictions where their end users are located</li>
        </ul>

        <h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">4.3 Withdrawal of Consent</h3>
        <p>
          End users may withdraw consent at any time by revoking microphone permissions in their browser or by
          switching to text-only mode. Account holders may disable the voice feature entirely from their dashboard.
        </p>
      </section>

      {/* 5. Illinois BIPA */}
      <section id="bipa">
        <h2 className="text-xl font-bold text-gray-900 mt-10 mb-4">5. Illinois BIPA Compliance</h2>
        <p>
          The Illinois Biometric Information Privacy Act ("BIPA"), 740 ILCS 14, imposes specific requirements on
          the collection and handling of biometric identifiers and biometric information. We address each
          requirement below.
        </p>

        <h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">5.1 Written Policy (Section 15(a))</h3>
        <p>
          This Biometric Data Policy serves as our publicly available written policy establishing a retention
          schedule and guidelines for permanently destroying biometric data. Voice data is destroyed immediately
          after processing (raw audio) or in accordance with the account holder's retention settings
          (transcriptions).
        </p>

        <h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">5.2 Informed Consent (Section 15(b))</h3>
        <p>
          Before collecting biometric data, we inform the end user in writing (via the chat widget notice) that
          biometric data is being collected, the specific purpose of collection, and the duration for which it
          will be stored. We obtain the end user's written release (electronic consent via affirmative action)
          before processing.
        </p>

        <h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">5.3 Prohibition on Sale (Section 15(c))</h3>
        <p>
          We do not sell, lease, trade, or otherwise profit from biometric data. We do not disclose biometric data
          to third parties except as required to process speech-to-text conversion through our service provider,
          which is contractually prohibited from using the data for any other purpose.
        </p>

        <h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">5.4 Storage and Protection (Section 15(e))</h3>
        <p>
          We store and transmit biometric data using a standard of care that is at least as protective as the
          standard we apply to other confidential and sensitive information. Specific measures include TLS 1.2+
          encryption in transit, AES-256 encryption at rest, and strict access controls.
        </p>

        <h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">5.5 Destruction Schedule</h3>
        <p>
          Biometric data is destroyed when the initial purpose for collection has been satisfied or within three
          years of the individual's last interaction with the Service, whichever occurs first. Raw audio is
          destroyed immediately after processing.
        </p>
      </section>

      {/* 6. Texas CUBI */}
      <section id="texas-cubi">
        <h2 className="text-xl font-bold text-gray-900 mt-10 mb-4">6. Texas CUBI Compliance</h2>
        <p>
          The Texas Capture or Use of Biometric Identifier Act ("CUBI"), Tex. Bus. & Com. Code Ann. Section
          503.001, regulates the capture and use of biometric identifiers for commercial purposes.
        </p>
        <ul>
          <li><strong>Notice and consent:</strong> We provide notice and obtain consent before capturing biometric identifiers, as described in Section 4 of this policy.</li>
          <li><strong>Prohibition on sale:</strong> We do not sell biometric identifiers.</li>
          <li><strong>Storage security:</strong> We store, transmit, and protect biometric identifiers using reasonable care and in a manner that is the same as or more protective than the manner in which we store, transmit, and protect other confidential information.</li>
          <li><strong>Destruction:</strong> We destroy biometric identifiers within a reasonable time after the purpose for collection expires, and no later than the first anniversary of the date the purpose expires (for stored transcriptions). Raw audio is destroyed immediately.</li>
        </ul>
      </section>

      {/* 7. Washington */}
      <section id="washington-biometric">
        <h2 className="text-xl font-bold text-gray-900 mt-10 mb-4">7. Washington Biometric Law Compliance</h2>
        <p>
          Washington state's biometric privacy law (RCW 19.375) requires notice and consent before enrolling
          biometric identifiers in a database for a commercial purpose.
        </p>
        <ul>
          <li><strong>No enrollment in database:</strong> We do not enroll voice data in a biometric database. Voice data is processed transiently for speech-to-text conversion and is not stored in a manner that constitutes a biometric database.</li>
          <li><strong>Notice:</strong> We provide clear notice to end users that voice data is being processed, as described in Section 4.</li>
          <li><strong>Consent:</strong> We obtain consent through the affirmative actions described in Section 4.1.</li>
          <li><strong>No sale or disclosure:</strong> We do not sell or disclose biometric identifiers except as necessary to provide the Service.</li>
          <li><strong>Security:</strong> We protect biometric data using industry-standard security practices consistent with the protections described in this policy.</li>
        </ul>
      </section>

      {/* 8. Other State Laws */}
      <section id="other-state-laws">
        <h2 className="text-xl font-bold text-gray-900 mt-10 mb-4">8. Other State Biometric Laws</h2>
        <p>
          Several other states have enacted or are considering biometric data legislation. We monitor these
          developments and comply with applicable requirements, including but not limited to:
        </p>

        <h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">8.1 New York</h3>
        <p>
          New York City's biometric identifier information law (NYC Admin Code Section 22-1201 et seq.) requires
          commercial establishments to post signage regarding biometric data collection. As a SaaS provider, this
          law applies to physical locations, not online services. However, account holders who operate physical
          businesses using voice-enabled kiosks should assess their own compliance obligations.
        </p>

        <h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">8.2 Colorado, Connecticut, Virginia, and Other State Privacy Laws</h3>
        <p>
          Comprehensive state privacy laws in Colorado (CPA), Connecticut (CTDPA), Virginia (VCDPA), and similar
          states classify biometric data as "sensitive data" requiring opt-in consent before processing. Our
          consent mechanism (Section 4) satisfies these opt-in requirements.
        </p>

        <h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">8.3 Ongoing Compliance</h3>
        <p>
          We regularly review our biometric data practices against new and evolving state laws. If changes to our
          practices are required, we will update this policy and notify affected account holders.
        </p>
      </section>

      {/* 9. User Rights */}
      <section id="bio-user-rights">
        <h2 className="text-xl font-bold text-gray-900 mt-10 mb-4">9. User Rights Regarding Biometric Data</h2>
        <p>
          In addition to the general user rights described in our Privacy Policy, the following rights apply
          specifically to biometric data:
        </p>
        <ul>
          <li><strong>Right to information:</strong> You may request details about what biometric data we have collected, how it was used, and to whom it has been disclosed.</li>
          <li><strong>Right to access:</strong> You may request access to transcriptions of your voice conversations. Raw audio recordings are not available because they are not retained.</li>
          <li><strong>Right to deletion:</strong> You may request immediate deletion of any stored transcriptions derived from voice data.</li>
          <li><strong>Right to opt out:</strong> You may stop all biometric data collection by revoking microphone access or switching to text mode.</li>
          <li><strong>Right to object to processing:</strong> You may object to the processing of your voice data. We will cease processing promptly.</li>
        </ul>
        <p>
          Account holders may exercise these rights on behalf of their end users. End users may also contact us
          directly at{' '}
          <a href="mailto:legal@smbchat.com" className="text-violet-600 hover:text-violet-700">
            legal@smbchat.com
          </a>
          .
        </p>
      </section>

      {/* 10. Deletion Procedures */}
      <section id="bio-deletion">
        <h2 className="text-xl font-bold text-gray-900 mt-10 mb-4">10. Deletion Procedures</h2>

        <h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">10.1 Automatic Deletion</h3>
        <ul>
          <li><strong>Raw audio:</strong> Automatically deleted from memory after speech-to-text processing completes (typically within 30 seconds)</li>
          <li><strong>Voice characteristics:</strong> Never stored; exist only transiently in processing memory</li>
          <li><strong>Transcriptions:</strong> Automatically deleted according to the account holder's retention settings (default: 90 days)</li>
        </ul>

        <h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">10.2 Manual Deletion</h3>
        <p>Account holders may manually delete voice transcriptions at any time through the dashboard by:</p>
        <ul>
          <li>Deleting individual conversations that contain voice transcriptions</li>
          <li>Bulk-deleting conversation logs by date range</li>
          <li>Deleting all conversation data from the account settings page</li>
        </ul>

        <h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">10.3 Deletion Requests</h3>
        <p>
          End users or account holders may submit deletion requests to{' '}
          <a href="mailto:legal@smbchat.com" className="text-violet-600 hover:text-violet-700">
            legal@smbchat.com
          </a>
          . We will process deletion requests within 15 business days and confirm completion in writing.
        </p>

        <h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">10.4 Verification of Deletion</h3>
        <p>
          Upon request, we will provide written certification that biometric data has been destroyed in accordance
          with this policy and applicable law.
        </p>
      </section>

      {/* Contact */}
      <section className="mt-12 pt-8 border-t border-gray-200">
        <h2 className="text-xl font-bold text-gray-900 mb-4">Contact</h2>
        <p>For questions about biometric data practices:</p>
        <p className="mt-2">
          <strong>Start My Business Inc.</strong>
          <br />
          Email:{' '}
          <a href="mailto:legal@smbchat.com" className="text-violet-600 hover:text-violet-700">
            legal@smbchat.com
          </a>
          <br />
          Website: smbchat.alwaysencrypted.com
        </p>
      </section>
    </article>
  )
}
